### ISSUE TITLE
Unable to install  ROI.plugin.gurobi

### ISSUE THREAD

**Issue by Hujinii** [FlorianSchwendinger/ROI.plugin.gurobi7#2]
Hi, I tired to install ROI.plugin,gurobi, but R always reported errors 
I work R version 4.1.1 (2021-08-10) using Rstudio on a win10 system. 
I have first installed library "Gurobi" via 
install.packages('C:/Program Files (x86)/win64/R/gurobi_9.1-2.zip', repos=NULL)

It seems that the library is installed successfully and I can load the library.

Install.packages('C:/Program Files (x86)/win64/R/gurobi_9.1-2.zip', repos=NULL)
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
package ‘gurobi’ successfully unpacked and MD5 sums checked

(However, I could not load any data under the gurobi library.)

Then I use the following code, and it reports the failutre. 
>library(slam)
> library(gurobi)
> install_github("FlorianSchwendinger/ROI.plugin.gurobi", INSTALL_opts="--no-multiarch")
Downloading GitHub repo FlorianSchwendinger/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
√  checking for file 'C:\Users\3873277\AppData\Local\Temp\RtmpCKWcXA\remotes77941f5b63b3\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION' (763ms)
-  preparing 'ROI.plugin.gurobi':
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ROI.plugin.gurobi_0.4-0.tar.gz'
   
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/3873277/AppData/Local/Temp/RtmpCKWcXA/file77946753532b/ROI.plugin.gurobi_0.4-0.tar.gz’ had non-zero exit status

Could you please let me know whats wrong with it. Is there any possible solution? Thanks so much in advance.
Best, Jing

**Comment by FlorianSchwendinger** [comment]
You should try https://github.com/roigrp/ROI.plugin.gurobi !

As the README of 
https://github.com/FlorianSchwendinger/ROI.plugin.gurobi7 states, it
was tested on Debian GNU/Linux 8 (jessie) with the gurobi versions 6.5 and 7.
